### ISSUE TITLE
Public SSH must be present for all users

### ISSUE THREAD

**Issue by venekamp** [venekamp/nowfap-portal#15]
It appears that for all users their public SSH keys must be present.

When a user is added to COmanage and does not have a public SSH key yet, the non existent public SSH key will be ignored. However, subsequent provisioning of the the same user will fail due to a missing uid, as required by the ldapPublicKey schema.

Seems to be links to issue: [CO-1397](https://bugs.internet2.edu/jira/browse/CO-1397)

**Comment by baszoetekouw** [comment]
Ik kan dit binnen het SCZ-pilotplatform niet reproduceren. Wijzigingen in gebruikers met en zonder ssh key komen beide in de ldap aan.  Ook van scratch reprovisionen van de gebruikers werkt prima.

**Comment by baszoetekouw** [comment]
@muisit Zou dit gerelateerd kunnen zijn aan het `uid=>TRUE` issue dat we eerder deze week hebben opgelost?  Merk op: Gerben gebruikt de standaard COmanage ldap plugin.

**Comment by muisit** [comment]
Die uid=>TRUE was een bug, dat had echt uid=>uid moeten zijn. Maar het feit dat die regel er stond betekende dat de uid uitgegenereerd had moeten worden. Dit probleem speelt dus idd niet in de SCZ en dit is het enige punt ook waarin de fixedldapprovisioner afwijkt, qua attribute-generatie, van de reguliere ldapprovisioner

**Comment by venekamp** [comment]
Nadat ik een vinkje voor uid in inetOrgPerson had aangezet voor de LdapPlugin is het probleem opgelost.

**Comment by marksantcroos** [comment]
Is dat per ProvisioningTarget of op 1 plek?

**Comment by venekamp** [comment]
Het gaat om de configuratie van de plug in zelf en dus ja, voor elke geconfigureerde plugin.

**Comment by marksantcroos** [comment]
Heb je dat ook voor de LUMC target gedaan? Want dat staat al aan.
